{% set name = "ndarray_listener" %}
{% set version = "1.0.15" %}
{% set sha256 = "c864df83d55a8c40a3dc96e58abfe6ee647d4a71501d1f629ae86cb96959a9e4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - numpy

test:
  requires:
    - pytest
  imports:
    - ndarray_listener
  commands:
    - python -c "import ndarray_listener; ndarray_listener.test()"

about:
  home: https://github.com/Horta/ndarray_listener
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Implementation of the Observer pattern for NumPy arrays.'
  doc_url: https://github.com/Horta/ndarray_listener
  dev_url: https://github.com/Horta/ndarray_listener

extra:
  recipe-maintainers:
    - Horta
