travis:
  secure:
    BINSTAR_TOKEN: PrFXtuml8eMfK0fdLFidNW44+MtVaGqLNctKUKVVyieSgBPAeSrhkl+k+EvkMHq4iXxbYATVyNsbh522lImjc3G4f14greic+jqykkJW0dGLf7MYM4gB1MKsBGau095IHf5Az1DbnvfvIs/NSISIGRrzB6jea4KBelGLcFlQbZw27O7MwW/RtKObmjRepcON3K4kr4mzoOagZI5FsqcWtywlbLFPKpSQSOlaUf/TIZjUU/eVn8bEdA2hLC+BoG0DYYKQDz3h+GoKUgpO+8b4qcyBkylj1/mvOuvIyD7/4UmAeGoC0qh4bbSdXh7PugLwL9Ha+pa48U8TcBqeF81vy+B0JxVUd3qjw8iEVeP2iOPH7+gWQyQ8df8joLHawFMC1nRAk3f3i7NvkwVJvq9Ty32e0Mb8uWIq+eQs1H8t1LrmpxISRezLabjpj63/0rjfu/PkNRiJDVW7QWD/hX4pXVZFyg+6jQIy61g3GxmW0ZIgcJQbzwiA970Vpl4EUO9I0pCOcKtVHLdSqtMPllHbJzA8fQIpdO2X83TZlGP7JQc5sBDB29eEBKKAjisyNySvZMYOG0P0SCSvqawxE7R/TLs2XZXcrlUSpZRAY3Ht3q0umATbL2IjZ8owWakddSQqyc2UGrTHRV/lEqkZ2WfLsrz25mM2UgW91KE9YkFkTgs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
